spring.application.name=progetto

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8443/realms/NegAnt
server.forward-headers-strategy=native
server.address=127.0.0.1
server.servlet.context-path=/api
#server.port=9999
#server.ssl.key-store=classpath:springboot.p12
#server.ssl.key-store-password=Spr1nG600t
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=SpringBootNegAnt
#server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
#server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

# Dentro vault
#spring.security.user.name=adminUser 
#spring.security.user.password=S3cureP@ssw0rd!
