name: CI Pipeline (Test & SAST)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # JOB 1: BACK-END (Spring Boot + Maven)
  # ==========================================
  backend-test:
    name: Spring Boot Tests & Build
    runs-on: windows-latest
    # Diciamo a GitHub in quale cartella eseguire i comandi
    defaults:
      run:
        working-directory: ./back-end 

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'Oracle'
        cache: maven # Velocizza le build future salvando in cache le dipendenze

  # ==========================================
  # JOB 2: FRONT-END (Angular)
  # ==========================================
  frontend-test:
    name: Angular Lint & Tests
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './front-end/package-lock.json'

    - name: Installa Dipendenze
      run: npm ci

    - name: Analisi Statica (Linting)
      run: npm run lint